export type DivisionProps = JSX.IntrinsicElements["div"]
export type ButtonProps = JSX.IntrinsicElements["button"]
export type VectorProps = JSX.IntrinsicElements["svg"]
export type AnchorProps = JSX.IntrinsicElements["a"]
export type ImageProps = JSX.IntrinsicElements["img"]
export type InputProps = JSX.IntrinsicElements["input"]
export type TextareaProps = JSX.IntrinsicElements["textarea"]